spring:
  application:
    name: hms

  datasource:
    # Example for PostgreSQL. Update URL, username and password for your environment.
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/hmsdb}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update # validate | update | create | create-drop depending on lifecycle
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:https://ngcloak.onrender.com/realms/hmsRealm}
          keycloak-patient:
            issuer-uri: ${PATIENT_ISSUER_URI:https://ngcloak.onrender.com/realms/hms-patient}

        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_STAFF_CLIENT_ID:${KEYCLOAK_CLIENT_ID:hmsClient}}
            client-secret: ${KEYCLOAK_STAFF_CLIENT_SECRET:${KEYCLOAK_CLIENT_SECRET:w9nMST2lsepWTz7DYhAwkI68pFoVVbJ4}}
            authorization-grant-type: authorization_code
            scope: openid,profile,email

          keycloak-patient:
            provider: keycloak-patient
            client-id: ${KEYCLOAK_PATIENT_CLIENT_ID:hms-patient-client}
            client-secret: ${KEYCLOAK_PATIENT_CLIENT_SECRET:3FzJ2fULq6i8B60fpbB2zHJU5NjScVz8}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
server:
  port: 9112


keycloak:
  base-url: ${KEYCLOAK_BASE_URL:https://ngcloak.onrender.com}
  realm: ${KEYCLOAK_REALM:hmsRealm}
  client-id: ${KEYCLOAK_CLIENT_ID:hmsClient}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:w9nMST2lsepWTz7DYhAwkI68pFoVVbJ4}
  grant-type: ${KEYCLOAK_GRANT_TYPE:client_credentials}
  patient:
    realm: ${KEYCLOAK_PATIENT_REALM:hms-patient}
    client-id: ${KEYCLOAK_PATIENT_CLIENT_ID:hms-patient-client}
    client-secret: ${KEYCLOAK_PATIENT_CLIENT_SECRET:3FzJ2fULq6i8B60fpbB2zHJU5NjScVz8}
